# Generated by Django 5.0.1 on 2024-10-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_log_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('login', 'User login'), ('logout', 'User logout'), ('register', 'User register'), ('order_success', 'User order success'), ('order_failed', 'User order failed'), ('email_verification_success', 'User email verification success'), ('email_verification_failed', 'User email verification failed')], max_length=50),
        ),
    ]
